//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace WebServiceRest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Reservation
    {
        public int IdReservation { get; set; }
        public int IdUser { get; set; }
        public DateTime FirstNight { get; set; }
        public DateTime LastNight { get; set; }
        public bool Cancelled { get; set; }
        public double Price { get; set; }

        [NotMapped]
        public List<Room> Rooms { get; set; } = new List<Room>();

    }
}
