//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsInReservation
    {
        public int Id { get; set; }
        public int IdRoom { get; set; }
        public int IdReservation { get; set; }
    }
}
