//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceRest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VB_WebServiceDB : DbContext
    {
        public VB_WebServiceDB()
            : base("name=VB_WebServiceDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<UserData> UserDatas { get; set; }
    
        public virtual ObjectResult<GetAllEmptyRoomsAtDateRange_Result> GetAllEmptyRoomsAtDateRange(Nullable<System.DateTime> firstNight, Nullable<System.DateTime> lastNight)
        {
            var firstNightParameter = firstNight.HasValue ?
                new ObjectParameter("firstNight", firstNight) :
                new ObjectParameter("firstNight", typeof(System.DateTime));
    
            var lastNightParameter = lastNight.HasValue ?
                new ObjectParameter("lastNight", lastNight) :
                new ObjectParameter("lastNight", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllEmptyRoomsAtDateRange_Result>("GetAllEmptyRoomsAtDateRange", firstNightParameter, lastNightParameter);
        }
    
        public virtual ObjectResult<string> GetDistinctPictureUrlFromHotelId(Nullable<int> idHotel)
        {
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("IdHotel", idHotel) :
                new ObjectParameter("IdHotel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetDistinctPictureUrlFromHotelId", idHotelParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> GetHotelOccupationAtDateFromId(Nullable<System.DateTime> date, Nullable<int> idHotel)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("IdHotel", idHotel) :
                new ObjectParameter("IdHotel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetHotelOccupationAtDateFromId", dateParameter, idHotelParameter);
        }
    }
}
